In [15]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [16]:
 iris=load_iris()
#load_iris関数でロードしている

In [17]:
iris
#iris:アヤメ　品種分類を目指す
#以下説明
#Attributeの意味{sepal length:がくの長さ,sepal width:がくの幅,petal length:花弁の長さ,petal width:花弁の幅}

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
print(iris.target_names)
#花の種類が格納されている

['setosa' 'versicolor' 'virginica']


In [19]:
for data,target in zip(iris.data[:5],iris.target[:5]):
    print(data,target)
#がくの長さ、幅、花弁の長さ、幅の特徴量

[5.1 3.5 1.4 0.2] 0
[4.9 3.  1.4 0.2] 0
[4.7 3.2 1.3 0.2] 0
[4.6 3.1 1.5 0.2] 0
[5.  3.6 1.4 0.2] 0


In [20]:
df =pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

In [21]:
x=iris.data[50:,2].reshape(-1,1)
y=iris.data[50:]-1
#x,yの50行から二列取り出す

In [22]:
x

array([[4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
       [4. ],
       [4.9],
       [4.7],
       [4.3],
       [4.4],
       [4.8],
       [5. ],
       [4.5],
       [3.5],
       [3.8],
       [3.7],
       [3.9],
       [5.1],
       [4.5],
       [4.5],
       [4.7],
       [4.4],
       [4.1],
       [4. ],
       [4.4],
       [4.6],
       [4. ],
       [3.3],
       [4.2],
       [4.2],
       [4.2],
       [4.3],
       [3. ],
       [4.1],
       [6. ],
       [5.1],
       [5.9],
       [5.6],
       [5.8],
       [6.6],
       [4.5],
       [6.3],
       [5.8],
       [6.1],
       [5.1],
       [5.3],
       [5.5],
       [5. ],
       [5.1],
       [5.3],
       [5.5],
       [6.7],
       [6.9],
       [5. ],
       [5.7],
      

In [23]:
y

array([[6. , 2.2, 3.7, 0.4],
       [5.4, 2.2, 3.5, 0.5],
       [5.9, 2.1, 3.9, 0.5],
       [4.5, 1.3, 3. , 0.3],
       [5.5, 1.8, 3.6, 0.5],
       [4.7, 1.8, 3.5, 0.3],
       [5.3, 2.3, 3.7, 0.6],
       [3.9, 1.4, 2.3, 0. ],
       [5.6, 1.9, 3.6, 0.3],
       [4.2, 1.7, 2.9, 0.4],
       [4. , 1. , 2.5, 0. ],
       [4.9, 2. , 3.2, 0.5],
       [5. , 1.2, 3. , 0. ],
       [5.1, 1.9, 3.7, 0.4],
       [4.6, 1.9, 2.6, 0.3],
       [5.7, 2.1, 3.4, 0.4],
       [4.6, 2. , 3.5, 0.5],
       [4.8, 1.7, 3.1, 0. ],
       [5.2, 1.2, 3.5, 0.5],
       [4.6, 1.5, 2.9, 0.1],
       [4.9, 2.2, 3.8, 0.8],
       [5.1, 1.8, 3. , 0.3],
       [5.3, 1.5, 3.9, 0.5],
       [5.1, 1.8, 3.7, 0.2],
       [5.4, 1.9, 3.3, 0.3],
       [5.6, 2. , 3.4, 0.4],
       [5.8, 1.8, 3.8, 0.4],
       [5.7, 2. , 4. , 0.7],
       [5. , 1.9, 3.5, 0.5],
       [4.7, 1.6, 2.5, 0. ],
       [4.5, 1.4, 2.8, 0.1],
       [4.5, 1.4, 2.7, 0. ],
       [4.8, 1.7, 2.9, 0.2],
       [5. , 1.7, 4.1, 0.6],
       [4.4, 2

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [25]:
#標準化を行う関数StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

In [26]:
x_scaled
#標準化されたデータ

array([[-0.25077906],
       [-0.49425387],
       [-0.00730424],
       [-1.10294091],
       [-0.37251647],
       [-0.49425387],
       [-0.25077906],
       [-1.95510276],
       [-0.37251647],
       [-1.22467832],
       [-1.71162795],
       [-0.8594661 ],
       [-1.10294091],
       [-0.25077906],
       [-1.58989054],
       [-0.61599128],
       [-0.49425387],
       [-0.9812035 ],
       [-0.49425387],
       [-1.22467832],
       [-0.12904165],
       [-1.10294091],
       [-0.00730424],
       [-0.25077906],
       [-0.73772869],
       [-0.61599128],
       [-0.12904165],
       [ 0.11443316],
       [-0.49425387],
       [-1.71162795],
       [-1.34641572],
       [-1.46815313],
       [-1.22467832],
       [ 0.23617057],
       [-0.49425387],
       [-0.49425387],
       [-0.25077906],
       [-0.61599128],
       [-0.9812035 ],
       [-1.10294091],
       [-0.61599128],
       [-0.37251647],
       [-1.10294091],
       [-1.95510276],
       [-0.8594661 ],
       [-0

In [27]:
X_train,x_test,Y_train,y_test=train_test_split(x_scaled,y,random_state=0)

In [28]:
log_reg=LogisticRegression().fit(X_train,Y_train)

C:\Users\mkou0\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: bad input shape (75, 4)

In [ ]:
log_reg.intercept_,log_reg.coef_