In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [4]:
arr1=np.arange(9).reshape((3,3))

In [5]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1=Series([0,1,2],index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [15]:
pd.concat([ser1,ser2],axis=1)

C:\Users\mkou0\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [16]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [19]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [20]:
dframe1

X         Y         Z
0  0.929821  1.277747 -0.625316
1 -0.994337  2.643987  0.231938
2 -0.502169 -1.084732 -0.806156
3  0.391609  0.380124 -1.469046

In [21]:
dframe2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [22]:
dframe2

Y         Q         X
0  0.928683  0.171726 -0.169694
1 -0.028459 -1.065430  1.554052
2 -2.285770 -0.388104 -0.047496

In [23]:
pd.concat([dframe1,dframe2])

C:\Users\mkou0\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.929821  1.277747 -0.625316
1       NaN -0.994337  2.643987  0.231938
2       NaN -0.502169 -1.084732 -0.806156
3       NaN  0.391609  0.380124 -1.469046
0  0.171726 -0.169694  0.928683       NaN
1 -1.065430  1.554052 -0.028459       NaN
2 -0.388104 -0.047496 -2.285770       NaN

In [24]:
pd.concat([dframe1,dframe2],ignore_index=True)

C:\Users\mkou0\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.929821  1.277747 -0.625316
1       NaN -0.994337  2.643987  0.231938
2       NaN -0.502169 -1.084732 -0.806156
3       NaN  0.391609  0.380124 -1.469046
4  0.171726 -0.169694  0.928683       NaN
5 -1.065430  1.554052 -0.028459       NaN
6 -0.388104 -0.047496 -2.285770       NaN