In [1]:
import numpy as np

In [39]:
arr=np.arange(5)

In [40]:
arr

array([0, 1, 2, 3, 4])

In [41]:
np.save('my_array',arr)

In [42]:
arr1=np.load('my_array.npy')

In [43]:
arr=np.arange(10)

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr2=np.arange(10)

In [46]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr1

array([0, 1, 2, 3, 4])

In [48]:
np.savez('ziparrays.npz',x=arr1,y=arr2)

In [49]:
archive_array=np.load('ziparrays.npz')

In [50]:
archive_array

In [51]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [53]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr=np.array([[1,2,3,4],[4,5,6,7]])

In [55]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [56]:
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [57]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])