In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

In [ ]:
iris=load_iris()
#load_iris関数でロードしている

In [5]:
iris
#iris:アヤメ　品種分類を目指す
#以下説明
#Attributeの意味{sepal length:がくの長さ,sepal width:がくの幅,petal length:花弁の長さ,petal width:花弁の幅}

NameError: name 'iris' is not defined

In [7]:
print(iris.target_names)
#花の種類が格納されている

NameError: name 'iris' is not defined

In [8]:
for data,target in zip(iris.data[:5],iris.target[:5]):
    print(data,target)
#がくの長さ、幅、花弁の長さ、幅の特徴量

NameError: name 'iris' is not defined

In [9]:
df =pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target
df

NameError: name 'pd' is not defined

In [7]:
x=iris.data[50:,2].reshape(-1,1)
y=iris.data[50:]-1
#x,yの50行から二列取り出す

In [8]:
x

array([[4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
       [4. ],
       [4.9],
       [4.7],
       [4.3],
       [4.4],
       [4.8],
       [5. ],
       [4.5],
       [3.5],
       [3.8],
       [3.7],
       [3.9],
       [5.1],
       [4.5],
       [4.5],
       [4.7],
       [4.4],
       [4.1],
       [4. ],
       [4.4],
       [4.6],
       [4. ],
       [3.3],
       [4.2],
       [4.2],
       [4.2],
       [4.3],
       [3. ],
       [4.1],
       [6. ],
       [5.1],
       [5.9],
       [5.6],
       [5.8],
       [6.6],
       [4.5],
       [6.3],
       [5.8],
       [6.1],
       [5.1],
       [5.3],
       [5.5],
       [5. ],
       [5.1],
       [5.3],
       [5.5],
       [6.7],
       [6.9],
       [5. ],
       [5.7],
      

In [9]:
y

array([[6. , 2.2, 3.7, 0.4],
       [5.4, 2.2, 3.5, 0.5],
       [5.9, 2.1, 3.9, 0.5],
       [4.5, 1.3, 3. , 0.3],
       [5.5, 1.8, 3.6, 0.5],
       [4.7, 1.8, 3.5, 0.3],
       [5.3, 2.3, 3.7, 0.6],
       [3.9, 1.4, 2.3, 0. ],
       [5.6, 1.9, 3.6, 0.3],
       [4.2, 1.7, 2.9, 0.4],
       [4. , 1. , 2.5, 0. ],
       [4.9, 2. , 3.2, 0.5],
       [5. , 1.2, 3. , 0. ],
       [5.1, 1.9, 3.7, 0.4],
       [4.6, 1.9, 2.6, 0.3],
       [5.7, 2.1, 3.4, 0.4],
       [4.6, 2. , 3.5, 0.5],
       [4.8, 1.7, 3.1, 0. ],
       [5.2, 1.2, 3.5, 0.5],
       [4.6, 1.5, 2.9, 0.1],
       [4.9, 2.2, 3.8, 0.8],
       [5.1, 1.8, 3. , 0.3],
       [5.3, 1.5, 3.9, 0.5],
       [5.1, 1.8, 3.7, 0.2],
       [5.4, 1.9, 3.3, 0.3],
       [5.6, 2. , 3.4, 0.4],
       [5.8, 1.8, 3.8, 0.4],
       [5.7, 2. , 4. , 0.7],
       [5. , 1.9, 3.5, 0.5],
       [4.7, 1.6, 2.5, 0. ],
       [4.5, 1.4, 2.8, 0.1],
       [4.5, 1.4, 2.7, 0. ],
       [4.8, 1.7, 2.9, 0.2],
       [5. , 1.7, 4.1, 0.6],
       [4.4, 2

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [11]:
#標準化を行う関数StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

In [12]:
x_scaled
#標準化されたデータ

array([[-0.25077906],
       [-0.49425387],
       [-0.00730424],
       [-1.10294091],
       [-0.37251647],
       [-0.49425387],
       [-0.25077906],
       [-1.95510276],
       [-0.37251647],
       [-1.22467832],
       [-1.71162795],
       [-0.8594661 ],
       [-1.10294091],
       [-0.25077906],
       [-1.58989054],
       [-0.61599128],
       [-0.49425387],
       [-0.9812035 ],
       [-0.49425387],
       [-1.22467832],
       [-0.12904165],
       [-1.10294091],
       [-0.00730424],
       [-0.25077906],
       [-0.73772869],
       [-0.61599128],
       [-0.12904165],
       [ 0.11443316],
       [-0.49425387],
       [-1.71162795],
       [-1.34641572],
       [-1.46815313],
       [-1.22467832],
       [ 0.23617057],
       [-0.49425387],
       [-0.49425387],
       [-0.25077906],
       [-0.61599128],
       [-0.9812035 ],
       [-1.10294091],
       [-0.61599128],
       [-0.37251647],
       [-1.10294091],
       [-1.95510276],
       [-0.8594661 ],
       [-0

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,random_state=0)

In [17]:
log_reg=LogisticRegression().fit(x_train,y_train)

C:\Users\mkou0\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: bad input shape (75, 4)

In [13]:
log_reg.intercept_,log_reg.coef_

NameError: name 'log_reg' is not defined